
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    in-memory: false


  data:
    mongodb:
      uri: mongodb://localhost:27017/test

server:
  port: 8080